name=AIP1640_LED_Matrix
version=1.0.0
author=Harmony Lab <teamproximal@gmail.com>
maintainer=Harmony Lab
sentence=A simple library for controlling the AIP1640 LED Matrix.
paragraph=This library provides an easy-to-use interface for driving an LED matrix based on the AIP1640 chip, enabling control over individual pixels and drawing patterns.
category=Display
architectures=*
url=https://github.com/Harmony-Maker-Club/AIP1640_LED_Matrix
